### ISSUE TITLE
Pdf tree import plugin added to https://github.com/GerritV/DotOPDS

### ISSUE THREAD

**Issue by gerritv** [DeniSix/DotOPDS#18]
FYI, I updated my repository with the working pdf tree importer. This uses iTextSharp to retrieve Info from pdf file.
It expects a Genre on command line for the top level. Each directory in the path to pdf file is added to the Genre list. Keywords, if any in the pdf, are indexed but not stored.

**Comment by shemanaev** [comment]
Added to readme. Good work 👍
