### ISSUE TITLE
After reaching last page in a search result, paging no longer available

### ISSUE THREAD

**Issue by hell-racer** [DeniSix/DotOPDS#2]
Use a reader (tested on Moon Reader Pro on Android).
1. Search for some term (or alternatively browse via genres).
2. Browse to the last page by entering its number (or alternatively go the last page but one, i.e. 108 of 109, and then tap ">").
3. At this point, paging is no longer available, page number is displayed as 1, despite it seems you are actually on the last page instead.

Please see attached screenshots for details (1 - the last page but one, 2 - the "last" page).

![1](https://cloud.githubusercontent.com/assets/20350033/16682883/6acbb118-4505-11e6-9e67-43b4b8be002c.png)
![2](https://cloud.githubusercontent.com/assets/20350033/16682890/7275f93c-4505-11e6-9164-be5466b73983.png)

**Comment by shemanaev** [comment]
I'm not sure why it's broken. Do you have any link to OPDS catalog with pagination that works? Couldn't find any. And i have the same behavior in flibusta's OPDS reaching last page.

**Comment by hell-racer** [comment]
Hi Denis! I've checked other catalogs, and it definitely seems like it's a reader's problem, not DotOPDS. I'll go ahead and close the issue. Thanks!
