### ISSUE TITLE
Search results aren't sorted

### ISSUE THREAD

**Issue by hell-racer** [DeniSix/DotOPDS#3]
Use a reader (tested on Moon Reader Pro).
1. Search for a term, or browse via Genres.
2. Search results aren't sorted, it's a bit difficult to find a book you need (e.g. you've searched for an author and then tried to find specific book by that author).

**Comment by shemanaev** [comment]
There was some problems sorting books by title. Maybe related to info extracting from books, i'm not sure why now. It needs some time to test and find out why i disabled it :smile:

**Comment by hell-racer** [comment]
Ok, thanks, no need to hurry :)

**Comment by shemanaev** [comment]
Should work with new version. Please report about non-working cases with special characters at start of title (like «).
Note, you need re-import library.

**Comment by gerritv** [comment]
Verified working on Moon Reader

**Comment by shemanaev** [comment]
Thanks for sharing.
